# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cwa.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tcwa.proto\"\x8a\x01\n\rQRCodePayload\x12\x0f\n\x07version\x18\x01 \x01(\r\x12$\n\x0clocationData\x18\x02 \x01(\x0b\x32\x0e.TraceLocation\x12-\n\x11\x63rowdNotifierData\x18\x03 \x01(\x0b\x32\x12.CrowdNotifierData\x12\x13\n\x0b\x63ountryData\x18\x04 \x01(\x0c\"t\n\rTraceLocation\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\x12\x16\n\x0estartTimestamp\x18\x05 \x01(\x04\x12\x14\n\x0c\x65ndTimestamp\x18\x06 \x01(\x04\"`\n\x11\x43rowdNotifierData\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x11\n\tpublicKey\x18\x02 \x01(\x0c\x12\x19\n\x11\x63ryptographicSeed\x18\x03 \x01(\x0c\x12\x0c\n\x04type\x18\x04 \x01(\r\"k\n\x0f\x43WALocationData\x12\x0f\n\x07version\x18\x01 \x01(\r\x12 \n\x04type\x18\x02 \x01(\x0e\x32\x12.TraceLocationType\x12%\n\x1d\x64\x65\x66\x61ultCheckInLengthInMinutes\x18\x03 \x01(\r*\xa1\x04\n\x11TraceLocationType\x12\x1d\n\x19LOCATION_TYPE_UNSPECIFIED\x10\x00\x12!\n\x1dLOCATION_TYPE_PERMANENT_OTHER\x10\x01\x12!\n\x1dLOCATION_TYPE_TEMPORARY_OTHER\x10\x02\x12\"\n\x1eLOCATION_TYPE_PERMANENT_RETAIL\x10\x03\x12(\n$LOCATION_TYPE_PERMANENT_FOOD_SERVICE\x10\x04\x12!\n\x1dLOCATION_TYPE_PERMANENT_CRAFT\x10\x05\x12%\n!LOCATION_TYPE_PERMANENT_WORKPLACE\x10\x06\x12\x33\n/LOCATION_TYPE_PERMANENT_EDUCATIONAL_INSTITUTION\x10\x07\x12+\n\'LOCATION_TYPE_PERMANENT_PUBLIC_BUILDING\x10\x08\x12*\n&LOCATION_TYPE_TEMPORARY_CULTURAL_EVENT\x10\t\x12)\n%LOCATION_TYPE_TEMPORARY_CLUB_ACTIVITY\x10\n\x12)\n%LOCATION_TYPE_TEMPORARY_PRIVATE_EVENT\x10\x0b\x12+\n\'LOCATION_TYPE_TEMPORARY_WORSHIP_SERVICE\x10\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cwa_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRACELOCATIONTYPE._serialized_start=480
  _TRACELOCATIONTYPE._serialized_end=1025
  _QRCODEPAYLOAD._serialized_start=14
  _QRCODEPAYLOAD._serialized_end=152
  _TRACELOCATION._serialized_start=154
  _TRACELOCATION._serialized_end=270
  _CROWDNOTIFIERDATA._serialized_start=272
  _CROWDNOTIFIERDATA._serialized_end=368
  _CWALOCATIONDATA._serialized_start=370
  _CWALOCATIONDATA._serialized_end=477
# @@protoc_insertion_point(module_scope)
