# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cwa.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cwa.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tcwa.proto\"\x8a\x01\n\rQRCodePayload\x12\x0f\n\x07version\x18\x01 \x01(\r\x12$\n\x0clocationData\x18\x02 \x01(\x0b\x32\x0e.TraceLocation\x12-\n\x11\x63rowdNotifierData\x18\x03 \x01(\x0b\x32\x12.CrowdNotifierData\x12\x13\n\x0b\x63ountryData\x18\x04 \x01(\x0c\"t\n\rTraceLocation\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\x12\x16\n\x0estartTimestamp\x18\x05 \x01(\x04\x12\x14\n\x0c\x65ndTimestamp\x18\x06 \x01(\x04\"`\n\x11\x43rowdNotifierData\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x11\n\tpublicKey\x18\x02 \x01(\x0c\x12\x19\n\x11\x63ryptographicSeed\x18\x03 \x01(\x0c\x12\x0c\n\x04type\x18\x04 \x01(\r\"k\n\x0f\x43WALocationData\x12\x0f\n\x07version\x18\x01 \x01(\r\x12 \n\x04type\x18\x02 \x01(\x0e\x32\x12.TraceLocationType\x12%\n\x1d\x64\x65\x66\x61ultCheckInLengthInMinutes\x18\x03 \x01(\r*\xa1\x04\n\x11TraceLocationType\x12\x1d\n\x19LOCATION_TYPE_UNSPECIFIED\x10\x00\x12!\n\x1dLOCATION_TYPE_PERMANENT_OTHER\x10\x01\x12!\n\x1dLOCATION_TYPE_TEMPORARY_OTHER\x10\x02\x12\"\n\x1eLOCATION_TYPE_PERMANENT_RETAIL\x10\x03\x12(\n$LOCATION_TYPE_PERMANENT_FOOD_SERVICE\x10\x04\x12!\n\x1dLOCATION_TYPE_PERMANENT_CRAFT\x10\x05\x12%\n!LOCATION_TYPE_PERMANENT_WORKPLACE\x10\x06\x12\x33\n/LOCATION_TYPE_PERMANENT_EDUCATIONAL_INSTITUTION\x10\x07\x12+\n\'LOCATION_TYPE_PERMANENT_PUBLIC_BUILDING\x10\x08\x12*\n&LOCATION_TYPE_TEMPORARY_CULTURAL_EVENT\x10\t\x12)\n%LOCATION_TYPE_TEMPORARY_CLUB_ACTIVITY\x10\n\x12)\n%LOCATION_TYPE_TEMPORARY_PRIVATE_EVENT\x10\x0b\x12+\n\'LOCATION_TYPE_TEMPORARY_WORSHIP_SERVICE\x10\x0c\x62\x06proto3'
)

_TRACELOCATIONTYPE = _descriptor.EnumDescriptor(
  name='TraceLocationType',
  full_name='TraceLocationType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LOCATION_TYPE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOCATION_TYPE_PERMANENT_OTHER', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOCATION_TYPE_TEMPORARY_OTHER', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOCATION_TYPE_PERMANENT_RETAIL', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOCATION_TYPE_PERMANENT_FOOD_SERVICE', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOCATION_TYPE_PERMANENT_CRAFT', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOCATION_TYPE_PERMANENT_WORKPLACE', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOCATION_TYPE_PERMANENT_EDUCATIONAL_INSTITUTION', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOCATION_TYPE_PERMANENT_PUBLIC_BUILDING', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOCATION_TYPE_TEMPORARY_CULTURAL_EVENT', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOCATION_TYPE_TEMPORARY_CLUB_ACTIVITY', index=10, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOCATION_TYPE_TEMPORARY_PRIVATE_EVENT', index=11, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOCATION_TYPE_TEMPORARY_WORSHIP_SERVICE', index=12, number=12,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=480,
  serialized_end=1025,
)
_sym_db.RegisterEnumDescriptor(_TRACELOCATIONTYPE)

TraceLocationType = enum_type_wrapper.EnumTypeWrapper(_TRACELOCATIONTYPE)
LOCATION_TYPE_UNSPECIFIED = 0
LOCATION_TYPE_PERMANENT_OTHER = 1
LOCATION_TYPE_TEMPORARY_OTHER = 2
LOCATION_TYPE_PERMANENT_RETAIL = 3
LOCATION_TYPE_PERMANENT_FOOD_SERVICE = 4
LOCATION_TYPE_PERMANENT_CRAFT = 5
LOCATION_TYPE_PERMANENT_WORKPLACE = 6
LOCATION_TYPE_PERMANENT_EDUCATIONAL_INSTITUTION = 7
LOCATION_TYPE_PERMANENT_PUBLIC_BUILDING = 8
LOCATION_TYPE_TEMPORARY_CULTURAL_EVENT = 9
LOCATION_TYPE_TEMPORARY_CLUB_ACTIVITY = 10
LOCATION_TYPE_TEMPORARY_PRIVATE_EVENT = 11
LOCATION_TYPE_TEMPORARY_WORSHIP_SERVICE = 12



_QRCODEPAYLOAD = _descriptor.Descriptor(
  name='QRCodePayload',
  full_name='QRCodePayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='QRCodePayload.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='locationData', full_name='QRCodePayload.locationData', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='crowdNotifierData', full_name='QRCodePayload.crowdNotifierData', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='countryData', full_name='QRCodePayload.countryData', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=152,
)


_TRACELOCATION = _descriptor.Descriptor(
  name='TraceLocation',
  full_name='TraceLocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='TraceLocation.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='TraceLocation.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='address', full_name='TraceLocation.address', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='startTimestamp', full_name='TraceLocation.startTimestamp', index=3,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='endTimestamp', full_name='TraceLocation.endTimestamp', index=4,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=270,
)


_CROWDNOTIFIERDATA = _descriptor.Descriptor(
  name='CrowdNotifierData',
  full_name='CrowdNotifierData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='CrowdNotifierData.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='publicKey', full_name='CrowdNotifierData.publicKey', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cryptographicSeed', full_name='CrowdNotifierData.cryptographicSeed', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='CrowdNotifierData.type', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=368,
)


_CWALOCATIONDATA = _descriptor.Descriptor(
  name='CWALocationData',
  full_name='CWALocationData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='CWALocationData.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='CWALocationData.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='defaultCheckInLengthInMinutes', full_name='CWALocationData.defaultCheckInLengthInMinutes', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=370,
  serialized_end=477,
)

_QRCODEPAYLOAD.fields_by_name['locationData'].message_type = _TRACELOCATION
_QRCODEPAYLOAD.fields_by_name['crowdNotifierData'].message_type = _CROWDNOTIFIERDATA
_CWALOCATIONDATA.fields_by_name['type'].enum_type = _TRACELOCATIONTYPE
DESCRIPTOR.message_types_by_name['QRCodePayload'] = _QRCODEPAYLOAD
DESCRIPTOR.message_types_by_name['TraceLocation'] = _TRACELOCATION
DESCRIPTOR.message_types_by_name['CrowdNotifierData'] = _CROWDNOTIFIERDATA
DESCRIPTOR.message_types_by_name['CWALocationData'] = _CWALOCATIONDATA
DESCRIPTOR.enum_types_by_name['TraceLocationType'] = _TRACELOCATIONTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QRCodePayload = _reflection.GeneratedProtocolMessageType('QRCodePayload', (_message.Message,), {
  'DESCRIPTOR' : _QRCODEPAYLOAD,
  '__module__' : 'cwa_pb2'
  # @@protoc_insertion_point(class_scope:QRCodePayload)
  })
_sym_db.RegisterMessage(QRCodePayload)

TraceLocation = _reflection.GeneratedProtocolMessageType('TraceLocation', (_message.Message,), {
  'DESCRIPTOR' : _TRACELOCATION,
  '__module__' : 'cwa_pb2'
  # @@protoc_insertion_point(class_scope:TraceLocation)
  })
_sym_db.RegisterMessage(TraceLocation)

CrowdNotifierData = _reflection.GeneratedProtocolMessageType('CrowdNotifierData', (_message.Message,), {
  'DESCRIPTOR' : _CROWDNOTIFIERDATA,
  '__module__' : 'cwa_pb2'
  # @@protoc_insertion_point(class_scope:CrowdNotifierData)
  })
_sym_db.RegisterMessage(CrowdNotifierData)

CWALocationData = _reflection.GeneratedProtocolMessageType('CWALocationData', (_message.Message,), {
  'DESCRIPTOR' : _CWALOCATIONDATA,
  '__module__' : 'cwa_pb2'
  # @@protoc_insertion_point(class_scope:CWALocationData)
  })
_sym_db.RegisterMessage(CWALocationData)


# @@protoc_insertion_point(module_scope)
